### ISSUE TITLE
I found issue while running in virtual environment 

### ISSUE THREAD

**Issue by faisalnazik** [BruceHenry/Movie-Django#3]
I already had installed the dependencies and migrated into database and created superuser successfully. 
After that when executed that command 
`python manage.py runserver`
all was good .. 
``Watching for file changes with StatReloader`
`Performing system checks...`

```
System check identified no issues (0 silenced).
October 06, 2020 - 22:35:11
Django version 3.1.2, using settings 'MovieHunter.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.`

```
But when I loaded the address in browser this error coming in terminal window . 
`Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /
[06/Oct/2020 22:35:30] "GET / HTTP/1.1" 400 68707`

Please tell me how to solve this . Thank You

**Comment by BruceHenry** [comment]
As the error message indicates, host needs to be added. 

There could be 2 solutions,
1. Adding "127.0.0.1" into MovieHunter/settings.py, line 27.
2. Use "localhost:8000" instead of "127.0.0.1:8000" to visit in the browser.

I think either of above could work.

**Comment by faisalnazik** [comment]
Thank you . It's working with solution 1 .
